Aggreagte Function

In [1]:
import numpy as np

In [4]:
a=np.array([11,22,33,44,55])
b=np.array([1,2,3,4,5])

In [5]:
a+b #universal function , ufunc

array([12, 24, 36, 48, 60])

In [6]:
np.sum(a)

165

In [7]:
np.average(a)

33.0

In [8]:
np.mean(a)

33.0

In [11]:
np.min(a)

11

In [12]:
np.max(a)

55

In [13]:
# on 2d array

In [14]:
arr1=np.arange(10,60,2).reshape(5,5)

In [15]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [16]:
np.sum(arr1)

850

In [17]:
np.mean(arr1)

34.0

In [18]:
np.max(arr1)

58

In [19]:
np.sum(arr1,axis=1)

array([ 70, 120, 170, 220, 270])

In [20]:
np.sum(arr1,axis=0)

array([150, 160, 170, 180, 190])

In [21]:
np.max(arr1,axis =0)

array([50, 52, 54, 56, 58])

In [22]:
np.max(arr1,axis=1)

array([18, 28, 38, 48, 58])

In [23]:
score=np.random.randint(10,100,15).reshape(5,3)

In [24]:
score

array([[62, 24, 77],
       [23, 89, 34],
       [15, 87, 93],
       [95, 48, 34],
       [75, 71, 89]])

In [25]:
np.max(score)

95

In [26]:
np.max(score,axis=0)

array([95, 89, 93])

In [27]:
np.max(score,axis=1)

array([77, 89, 93, 95, 89])

In [28]:
np.mean(score,axis=0)

array([54. , 63.8, 65.4])

In [29]:
np.mean(score,axis=1)

array([54.33333333, 48.66666667, 65.        , 59.        , 78.33333333])

In [30]:
np.sum(score,axis=1) #top to bottom : axis = 0 , left to right : axis = 1

array([163, 146, 195, 177, 235])

In [31]:
np.sum(score,axis=1)[4]

235

In [33]:
np.sum([75, 71, 89])

235

In [36]:
np.sum(score,axis=0)[2]

327

In [37]:
np.sum([77,34,93,34,89])

327