In [1]:
import numpy as np


In [8]:
arr1=np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [9]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
arr1.reshape(1,6)  # Row vector

array([[0, 1, 2, 3, 4, 5]])

In [12]:
arr1.reshape(6,1)  #Coloum Vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr1.reshape(1,-1) # numpy replace -1 by 6 in background for us

array([[0, 1, 2, 3, 4, 5]])

In [15]:
arr1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
arr1.reshape(-1,-1) # this will give error

ValueError: can only specify one unknown dimension

In [17]:
#Initial Placeholders



In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros([3,2]) # for 2d array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.zeros([3,4,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.zeros([5,4,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
#ones

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.ones([6,1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [32]:
np.ones([1,6])

array([[1., 1., 1., 1., 1., 1.]])

In [33]:
#identity Matrix

In [34]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np.eye(1)

array([[1.]])

In [38]:
#diag

In [40]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [41]:
np.diag([4,8,6])

array([[4, 0, 0],
       [0, 8, 0],
       [0, 0, 6]])

In [42]:
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [43]:
#Indexing and Slicing

In [44]:
#with 1d array

In [47]:
arr2=np.arange(5,15)
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
arr2[4]

9

In [49]:
arr2[-1]

14

In [50]:
arr2[-3]

12

In [51]:
arr2[6]

11

In [52]:
arr2[-4]

11

In [53]:
arr2[2:-1]

array([ 7,  8,  9, 10, 11, 12, 13])

In [54]:
arr2[:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
# With 2d array

In [57]:
arr3= np.arange(15).reshape(5,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [58]:
arr3[1]

array([3, 4, 5])

In [59]:
arr3[0]

array([0, 1, 2])

In [60]:
arr3[-1]

array([12, 13, 14])

In [61]:
arr3[-2]

array([ 9, 10, 11])

In [62]:
arr3[1:-1]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
arr3[2:5]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])