In [1]:
import numpy as np

In [2]:
data = np.loadtxt('fitbit.txt',dtype='str')

In [3]:
data

array([['6/10/2017', '5464', '200', '181', '6', '0', '68'],
       ['7/10/2017', '7167', '200', '208', '6', '0', '68'],
       ['8/10/2017', '9874', '300', '341', '5', '0', '68'],
       ['9/10/2017', '4969', '100', '190', '8', '0', '68'],
       ['10/10/2017', '8538', '300', '307', '5', '0', '68'],
       ['11/10/2017', '9875', '300', '302', '5', '0', '68'],
       ['12/10/2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8616'

In [4]:
type(data)

numpy.ndarray

In [5]:
data.shape

(26, 7)

In [6]:
data[0]

array(['6/10/2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [7]:
data[1]

array(['7/10/2017', '7167', '200', '208', '6', '0', '68'], dtype='<U10')

Data Cleaning

In [8]:
# data has no header
# data is in the form of string , cant be numerically compared



In [10]:
data.T

array([['6/10/2017', '7/10/2017', '8/10/2017', '9/10/2017', '10/10/2017',
        '11/10/2017', '12/10/2017', '13-10-2017', '14-10-2017',
        '15-10-2017', '16-10-2017', '17-10-2017', '18-10-2017',
        '19-10-2017', '20-10-2017', '21-10-2017', '22-10-2017',
        '23-10-2017', '24-10-2017', '25-10-2017', '26-10-2017',
        '27-10-2017', '28-10-2017', '29-10-2017', '30-10-2017',
        '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '329', 

In [11]:
date ,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = data.T


In [12]:
date

array(['6/10/2017', '7/10/2017', '8/10/2017', '9/10/2017', '10/10/2017',
       '11/10/2017', '12/10/2017', '13-10-2017', '14-10-2017',
       '15-10-2017', '16-10-2017', '17-10-2017', '18-10-2017',
       '19-10-2017', '20-10-2017', '21-10-2017', '22-10-2017',
       '23-10-2017', '24-10-2017', '25-10-2017', '26-10-2017',
       '27-10-2017', '28-10-2017', '29-10-2017', '30-10-2017',
       '31-10-2017'], dtype='<U10')

In [13]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [14]:
# changing the string data type to 'int'


In [15]:
step_count.dtype

dtype('<U10')

In [16]:
step_count=np.array(step_count,dtype='int')

In [17]:
calories_burned=np.array(calories_burned,dtype='int')

In [18]:
hours_of_sleep=np.array(hours_of_sleep,dtype='int')

In [19]:
weight_kg=np.array(weight_kg,dtype='int')

In [20]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [21]:
calories_burned

array([181, 208, 341, 190, 307, 302, 198, 201, 195, 327, 331, 318, 344,
       204, 180, 201, 329, 315, 197, 184, 328, 322, 327, 148, 235, 184])

In [22]:
hours_of_sleep

array([6, 6, 5, 8, 5, 5, 8, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 8, 8, 5, 5,
       5, 8, 6, 6])

In [23]:
weight_kg

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68])

In [24]:
weight_kg.dtype

dtype('int32')

In [25]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [26]:
np.unique(mood)  #this is not a numerical data but is a categorical data

array(['100', '200', '300'], dtype='<U10')

In [27]:
# 100 = sad
# 200 =  neutral
# 300 = happy


In [29]:
mood=='100'

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [30]:
mood=='200'

array([ True,  True, False, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False,  True,  True])

In [31]:
mood=='300'

array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False,  True,  True,  True, False, False, False])

In [32]:
mood[mood=='100']='Sad'
mood[mood=='200']='Neutral'
mood[mood=='300']='Happy'

In [33]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')

Data Analysing 

In [34]:
data

array([['6/10/2017', '5464', 'Neutral', '181', '6', '0', '68'],
       ['7/10/2017', '7167', 'Neutral', '208', '6', '0', '68'],
       ['8/10/2017', '9874', 'Happy', '341', '5', '0', '68'],
       ['9/10/2017', '4969', 'Sad', '190', '8', '0', '68'],
       ['10/10/2017', '8538', 'Happy', '307', '5', '0', '68'],
       ['11/10/2017', '9875', 'Happy', '302', '5', '0', '68'],
       ['12/10/2017', '4662', 'Sad', '198', '8', '0', '68'],
       ['13-10-2017', '6310', 'Neutral', '201', '6', '0', '68'],
       ['14-10-2017', '7556', 'Neutral', '195', '6', '0', '68'],
       ['15-10-2017', '9073', 'Happy', '327', '5', '0', '68'],
       ['16-10-2017', '9690', 'Happy', '331', '5', '0', '68'],
       ['17-10-2017', '9146', 'Happy', '318', '5', '0', '68'],
       ['18-10-2017', '9752', 'Happy', '344', '5', '0', '68'],
       ['19-10-2017', '6974', 'Neutral', '204', '6', '0', '68'],
       ['20-10-2017', '5619', 'Neutral', '180', '6', '0', '68'],
       ['21-10-2017', '6889', 'Neutral', '201', '6'

In [35]:
# max steps count

In [36]:
np.max(step_count)

9875

In [37]:
np.average(step_count)

7344.461538461538

In [38]:
np.argmax(step_count)

5

In [39]:
    # data on which max steps done

In [40]:
date[5]

'11/10/2017'

In [41]:
# frequency of mood


In [42]:
len(mood[mood=='Sad'])

5

In [43]:
len(mood[mood=='Neutral'])

9

In [44]:
len(mood[mood=='Happy'])

12

In [45]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [46]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([12,  9,  5], dtype=int64))